trigger:
  - master
jobs:
  - job: publish
    displayName: "Homelink"
    pool: # run locally to have access to proget pypi
      name: Container
      demands: agent.os -equals Linux
    container:
      image: python:3.13-slim
      env:
        PIP_INDEX_URL: https://pypi.org/simple
    steps:
      - checkout: self
        clean: true
      - script: pip install --user build
        displayName: Install build
      - script: python -m build -o $(System.ArtifactsDirectory)/Linux
        displayName: Build package
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: "current"
          downloadType: "specific"
          downloadPath: "$(System.ArtifactsDirectory)"
          itemPattern: "**"
      - script: pip install --user twine
        displayName: Install twine
      - task: TwineAuthenticate@0
        inputs:
          externalFeeds: pypi_upload
      - script: |
          ls '$(System.ArtifactsDirectory)/Linux'
          python -m twine upload --disable-progress-bar -r pypi --config-file $(PYPIRC_PATH) --verbose $(System.ArtifactsDirectory)/Linux/*
        displayName: Upload packages
